# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 21:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0074_totp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes for administrators regarding this user.', null=True, verbose_name='internal notes'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='page',
            field=models.CharField(db_index=True, max_length=30, validators=[django.core.validators.RegexValidator(b'^[pcs]:[a-z0-9]+$|^b:\\d+$', 'Page code must be ^[pcs]:[a-z0-9]+$|^b:\\d+$')], verbose_name='associated page'),
        ),
        migrations.AlterField(
            model_name='commentlock',
            name='page',
            field=models.CharField(db_index=True, max_length=30, validators=[django.core.validators.RegexValidator(b'^[pcs]:[a-z0-9]+$|^b:\\d+$', 'Page code must be ^[pcs]:[a-z0-9]+$|^b:\\d+$')], verbose_name='associated page'),
        ),
    ]
